version: "3"

services:
 
  api1:
    image: prac5_737 
    ports:
      - "3000:3000"
    networks:
      - my-network

  ui:
    image: prac5ui_737 
    ports:
      - "4200:80"
    environment:
      - SERVER_NAME=api1
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
